# Generated by Django 5.0 on 2024-03-08 18:25

import django.db.models.deletion
import myorder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productB', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=50, null=True)),
                ('random_number', models.CharField(default=myorder.models.generate_random_number, max_length=9)),
                ('payName', models.CharField(max_length=50, null=True)),
                ('payEmail', models.EmailField(max_length=254, null=True)),
                ('payAddress', models.CharField(max_length=100, null=True)),
                ('paycardNumber', models.CharField(max_length=16, null=True)),
                ('deliveryPrice', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
