# Generated by Django 5.0 on 2024-01-05 14:02

import django.utils.timezone
import myorder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userorder',
            name='random_number',
            field=models.CharField(default=myorder.models.generate_random_number, max_length=9),
        ),
    ]
