# Generated by Django 5.0 on 2024-01-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0002_userorder_created_userorder_random_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
