# Generated by Django 5.0 on 2024-01-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0003_alter_userorder_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='payEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='payName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='payaddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='paycardNumber',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
