# Generated by Django 5.0 on 2024-01-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0004_userorder_payemail_userorder_payname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='payaddress',
            new_name='payAddress',
        ),
    ]
