# Generated by Django 5.0 on 2024-01-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0005_rename_payaddress_userorder_payaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='deliveryPrice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
