# Generated by Django 5.0 on 2024-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shoesdetail',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='Color', to='shoes.color'),
        ),
        migrations.AddField(
            model_name='shoesdetail',
            name='genders',
            field=models.ManyToManyField(blank=True, related_name='genders', to='shoes.genders'),
        ),
        migrations.AddField(
            model_name='shoesdetail',
            name='shoe_Height',
            field=models.ManyToManyField(blank=True, related_name='shoe_Height', to='shoes.shoeheight'),
        ),
    ]
