# Generated by Django 5.0 on 2024-03-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_color_genders_shoeheight_shoesdetail_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesdetail',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='color', to='shoes.color'),
        ),
    ]
