# Generated by Django 5.0 on 2024-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoesdetail_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/'),
        ),
    ]
