# Generated by Django 5.0 on 2023-12-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
