# Generated by Django 5.0 on 2023-12-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_delete_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paydetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
