# Generated by Django 5.0 on 2024-01-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_userorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
